config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "api/resultado/:id", to: "home#resultado"
  get "api/resultado/", to: "home#resultado"

  resources :localidades
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cand.rb
class Cand
  include Mongoid::Document
  include Mongoid::Timestamps
  field :nm, type: String
  field :vap, type: String
  field :pvap, type: String
  field :seq, type: String
  belongs_to :resultado
end

app/models/localidade.rb
class Localidade
  include Mongoid::Document
  include Mongoid::Timestamps
  field :sigla, type: String
  field :nome, type: String
end

app/models/resultado.rb
class Resultado
  include Mongoid::Document
  include Mongoid::Timestamps
  field :dg, type: String
  field :hg, type: String
  field :datetime, type: String
  field :ele, type: String
  field :cdabr, type: String
  has_many :cand, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @resultados = Resultado.all.select{ |item| item[:pst].to_f > 0.0 }.sort_by!{|r| r.datetime.to_i}.reverse
        @localidades = Localidade.all
        # @resultado = Resultado.find("635f4277213c0deaa770bedf") #ultimo de presidente
        # puts @resultado.inspect
    end
    def resultado

        if params.key?(:id)
            @resultado = Resultado.find(params[:id])
        else
            @resultado = Resultado.find("635f4277213c0deaa770bedf")
        end
    
        render json: { html: render_to_string(partial: 'resultados/resultado', locals: {resultado: @resultado}) }

    end
   
end

app/controllers/localidades_controller.rb
class LocalidadesController < ApplicationController
  before_action :set_localidade, only: %i[ show edit update destroy ]

  # GET /localidades or /localidades.json
  def index
    @localidades = Localidade.all
  end

  # GET /localidades/1 or /localidades/1.json
  def show
  end

  # GET /localidades/new
  def new
    @localidade = Localidade.new
  end

  # GET /localidades/1/edit
  def edit
  end

  # POST /localidades or /localidades.json
  def create
    @localidade = Localidade.new(localidade_params)

    respond_to do |format|
      if @localidade.save
        format.html { redirect_to localidade_url(@localidade), notice: "Localidade was successfully created." }
        format.json { render :show, status: :created, location: @localidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @localidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localidades/1 or /localidades/1.json
  def update
    respond_to do |format|
      if @localidade.update(localidade_params)
        format.html { redirect_to localidade_url(@localidade), notice: "Localidade was successfully updated." }
        format.json { render :show, status: :ok, location: @localidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @localidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localidades/1 or /localidades/1.json
  def destroy
    @localidade.destroy

    respond_to do |format|
      format.html { redirect_to localidades_url, notice: "Localidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localidade
      @localidade = Localidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def localidade_params
      params.require(:localidade).permit(:sigla, :nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/views/home/index.html.erb
<head>
    <%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
</head>

<div class="container">
  <div class="main">
  <h1 class="title">Histórico 2º Turno</h1>
    <%= form_with(scope: "resultado") do |f| %>
      <div class="field">
        <%= f.label :tipo %><br />
        <%= f.select :tipo, %w(Presidente Governador), {include_blank: false } %>
        
        <%= f.label :localidade %><br />
        <%= f.select :localidade, @localidades.collect { |p| [ p.nome, p.sigla ] }, {include_blank: false } %>
        
        <%= f.label :horario, "Horario" %><br />
        <%= f.select :horario, Resultado.all.collect { |p| [ p.cdabr, p._id ] },{ include_blank: false }  %>
      
        </div>
    <% end %>
  <div id="resultados"></div>
  </div>
</div>





<script name="filterGorarioSelect" type="text/javascript">     


var resultados = new Array();
<% for resultado in @resultados -%>
    resultados.push(new Array('<%= resultado['cdabr'] %>', '<%=h resultado['datetime'] %>', '<%= resultado['_id'] %>', '<%= resultado['ele'] %>'));
<% end -%>
function localidadeSelected() {
  localidade = $('#resultado_localidade').val();
  tipo = $('#resultado_tipo').val() == "Presidente" ? "545" : "547"
  options = $("select#resultado_horario option").map(function() {return $(this).val();}).get();
  options.length = 1;
  resultados.forEach(function(resultado) {
    if (resultado[0].toLowerCase() == localidade.toLowerCase() && resultado[3] == tipo) {
      options[options.length] = new Option(resultado[1], resultado[2]);
    }
  });
  $("#resultado_horario").replaceOptions(options);
  
}

(function($, window) {
  $.fn.replaceOptions = function(options) {
    var self, $option;

    this.empty();
    self = this;

    $.each(options, function(index, option) {
      $option = $("<option></option>")
        .attr("value", option.value)
        .text(option.text);
      self.append($option);
    });
  };
  
})(jQuery, window);

  $('#resultado_localidade').on('change', function () {
    localidadeSelected()
    $("#resultados").empty();
  });
  $('#resultado_localidade').ready( localidadeSelected);
  $('#resultado_tipo').on('change', function() {
    options = $("select#resultado_horario option").map(function() {return $(this).val();}).get();
  options.length = 1;
  $("#resultado_horario").replaceOptions(options);
    $("#resultados").empty();

  });
 
</script>







<script name="renderTable" type="text/javascript">

 $('#resultado_horario').ready( renderApuracao);
  $(document).on("change", '#resultado_horario', renderApuracao);

  function renderApuracao(){
        var selectValue = $(this).val();
    
        $.ajax({
          url: "api/resultado/" + selectValue,
          type: "get",
          success: function(data) { 
            $("#resultados").empty();
            $("#resultados").append(data.html); 
          }
        })
     }


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Historico 2º Turno</title>
    <%= favicon_link_tag asset_path('election-box.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "global", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>


 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/localidades/_form.html.erb
<%= form_with(model: localidade) do |form| %>
  <% if localidade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(localidade.errors.count, "error") %> prohibited this localidade from being saved:</h2>

      <ul>
        <% localidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sigla, style: "display: block" %>
    <%= form.text_field :sigla %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/localidades/_localidade.html.erb
<div id="<%= dom_id localidade %>">
  <p>
    <strong>Sigla:</strong>
    <%= localidade.sigla %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= localidade.nome %>
  </p>

</div>

app/views/localidades/edit.html.erb
<h1>Editing localidade</h1>

<%= render "form", localidade: @localidade %>

<br>

<div>
  <%= link_to "Show this localidade", @localidade %> |
  <%= link_to "Back to localidades", localidades_path %>
</div>

app/views/localidades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Localidades</h1>

<div id="localidades">
  <% @localidades.each do |localidade| %>
    <%= render localidade %>
    <p>
      <%= link_to "Show this localidade", localidade %>
    </p>
  <% end %>
</div>

<%= link_to "New localidade", new_localidade_path %>

app/views/localidades/new.html.erb
<h1>New localidade</h1>

<%= render "form", localidade: @localidade %>

<br>

<div>
  <%= link_to "Back to localidades", localidades_path %>
</div>

app/views/localidades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @localidade %>

<div>
  <%= link_to "Edit this localidade", edit_localidade_path(@localidade) %> |
  <%= link_to "Back to localidades", localidades_path %>

  <%= button_to "Destroy this localidade", @localidade, method: :delete %>
</div>

app/views/resultados/_resultado.html.erb
<div id="tabela">
    <h5 id="apurados">Porcentagem apurada: <%= resultado['pst'] %>% </h5>
    <h6 id="horario">Ultima atualização: <%= resultado['datetime'] %></h6>

    <table class='table'>
        <thead>
            <td>#</td>
            <td>Nome</td>
            <td>Votos</td>
            <td>Porcentagem</td>
        </thead>
        <tbody>
            <% resultado['cand'].each do |candidato| %>
                <tr>
                <td><%= candidato['seq'] %></td>
                <td><%= candidato['nm'] %></td>
                <td><%= candidato['vap'].to_i  %></td>
                <td><%= candidato['pvap'] %>% </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>